### ISSUE TITLE
Kleine Verbesserungsvorschläge / Voraussetzungen nach MD

### ISSUE THREAD

**Issue by mira-miracoli** [johanna4711/Trans-in-3-Schritten#1]
Hi, ich finde euer Projekt sehr toll und ihr habt bestimmt viel Mühe da rein gesteckt und helft damit vielen Menschen.
Dennoch ein paar kleine Verbesserungsvorschläge und Gedanken von meiner Seite:
## Voraussetzungen

Eine OP oder HRT hat nur diese Voraussetzungen, wenn man sie über die Kasse abrechnen will, genauer hat also die Kostenübernahme diese Voraussetzungen und nicht die Maßnahme selbst.
Es gibt aber duchaus Menschen, die das nicht können (nichtbinär/ passen nicht in das Weltbild der KK oder andere persönliche Gründe, wie Aussicht auf Verbeamtung)
Diese Menschen können z.B. Surgeries über Privatbehandlungen im Ausland leichter bekommen und Hormone über den Schwarzmarkt oder Gender GP.
Ich denke es wäre besser, wenn ihr für sowas wie Voraussetzungen eine kritischere/objektivere Sprache nutzt.
z.B. "Bedingungen, die der medizinische Dienst der Krankenkassen häufig stellt um eine Kostenübernahme zu empfehlen"
oder ähnliches.
Ich glaube die vielen unkommentierten Bedingungen auf Reddit könnten Menschen, die am Anfang stehen, sonst schnell verunsichern (bin ich wirklich trans genug dafür?)

## Selbstbestimmungsgesetz
Zweiter Punkt wäre das Selbstbestimmungsgesetz. Es kommt mit sehr hoher Wahrscheinlichkeit innerhalb der nächsten paar Monate. Es lohnt sich also im Prinzip nicht mehr ein Verfahren nach TSG zu eröffnen, was vermultlich (mit ca 6 Monaten) länger dauert und die bekannten Nachteile und Unsicherheiten mit sich bringt. -> Ich fände es gut, diese kurz aufzuführen. Klar ist das Gesetz noch nicht durch aber ich würde auf jeden Fall am Anfang des Abschnitts darauf hinweisen. Auch auf die lange Dauer und die hohen Kosten.

Ein kleiner Typo: Es heißt  "Transsexuellengesetz" und nicht "Transsexuellenschutzgesetz". (es ist ja eher das Gegenteil)

**Comment by johanna4711** [comment]
Hi du, danke für das Feedback.

Eine HRT hat keine Voraussetzungen, da diese nicht genehmigt werden muss von der GKV (privat, keine Ahnung). Es ist aber so, dass es schwierig ist behandelnde Fachkräfte zu finden, die ohne Indikation die HRT offiziell begleiten (oder haben wir dich da falsch verstanden?). DIY geht immer, aber das wird hier nicht weiter ausgeführt.

Einige der Bedingungen (2 Gutachten z.b.) sind auch (noch, vllt ändert sich das wenn die Gutachten für das TSG wegfallen) von den (Top-) Kliniken (in DE) vorgeschrieben. Egal ob selbstzahlend oder nicht. Im Ausland wollen auch viele (meist die rennomierten Kliniken Facial Team, Suporn, ...) zumindest eine Indikation sehen.

"Disclaimer: Die Voraussetzungen die hier aufgeführt werden, sind nur für gültig für die gesetzlichen Krankenkassen. Die Anforderungen für die privaten Krankenkassen muss eins selbst bei der eigenen Krankenkasse erfragen." (Schreibfehler mal abgesehen dachten wir das sei so klar, dass das die Krankenkassen fordern sowie die ständigen Verweise auf die BGA und AWMF Leitlinien ...).

Selbstbestimmungsgesetz werden die Eckpunkte mal vorsichtig eingeführt. Trauen dem ganzen erst, wenn es auch wirklich da ist.

Aber danke nochmals, für dein Feedback und Mühe :)

**Comment by johanna4711** [comment]
Kein weiterer Kommentar -> closing.

(kann gerne wieder aufgemacht werden...)
